### ISSUE TITLE
6/27 branch: develop, issue: error

### ISSUE THREAD

**Issue by cesdea** [AniShorts/back-end#53]
## 개요
```
브랜치 통합을 시도할려고 했으나 관계설정 에러가 존재하여 에러 수정을 시도할려고 했으나 
관계설정의 오류의 경우 오류 코드에서 위치를 찾기 어려워 6/27에 했던 merge를 되돌리려서 commit으로 push 함
이후 에러의 시작지점을 찾기 위해 merge한 코드와 develop를 추가적으로 검사함
```
# develop
![캡처](https://github.com/AniShorts/back-end/assets/81796548/42f01341-70b1-47ab-b8ae-835c32a49d8a)

**Comment by Jiwonemil** [comment]
video, videolike, categoryvideo branch 수정 후 develop branch에 merge 완료
